In [1]:
"""
参考リスト
http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
-> scikit-learnの公式UserGuideの4.2.3、情報が豊富
"""
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [2]:
# CountVectrizerクラス
vectorizer = CountVectorizer()
print(vectorizer)

CountVectorizer()


In [3]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document? Yes it is.',
]
X = vectorizer.fit_transform(corpus)

print(type(corpus))
print(type(X))
print(X.toarray())
print(type(X.toarray()))

<class 'list'>
<class 'scipy.sparse._csr.csr_matrix'>
[[0 1 1 1 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 2 1 0 1 0]
 [1 0 0 0 0 1 0 1 1 0 0]
 [0 1 1 2 1 0 0 1 0 1 1]]
<class 'numpy.ndarray'>


In [4]:
print(vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'it' 'one' 'second' 'the' 'third' 'this'
 'yes']


In [5]:
import numpy as np
np.set_printoptions(precision=3)

transformer = TfidfTransformer(norm=None)
tfidf = transformer.fit_transform(X)

print(tfidf.toarray())
print(tfidf)

[[0.    1.223 1.511 1.223 0.    0.    0.    1.    0.    1.223 0.   ]
 [0.    1.223 0.    1.223 0.    0.    3.833 1.    0.    1.223 0.   ]
 [1.916 0.    0.    0.    0.    1.916 0.    1.    1.916 0.    0.   ]
 [0.    1.223 1.511 2.446 1.916 0.    0.    1.    0.    1.223 1.916]]
  (0, 9)	1.2231435513142097
  (0, 7)	1.0
  (0, 3)	1.2231435513142097
  (0, 2)	1.5108256237659907
  (0, 1)	1.2231435513142097
  (1, 9)	1.2231435513142097
  (1, 7)	1.0
  (1, 6)	3.83258146374831
  (1, 3)	1.2231435513142097
  (1, 1)	1.2231435513142097
  (2, 8)	1.916290731874155
  (2, 7)	1.0
  (2, 5)	1.916290731874155
  (2, 0)	1.916290731874155
  (3, 10)	1.916290731874155
  (3, 9)	1.2231435513142097
  (3, 7)	1.0
  (3, 4)	1.916290731874155
  (3, 3)	2.4462871026284194
  (3, 2)	1.5108256237659907
  (3, 1)	1.2231435513142097


In [6]:
import numpy as np

print(np.log((4.+1.)/(4.+1.)) + 1)
print(np.log((4.+1.)/(3.+1.)) + 1)
print(np.log((4.+1.)/(2.+1.)) + 1)
print(np.log((4.+1.)/(1.+1.)) + 1)

1.0
1.2231435513142097
1.5108256237659907
1.916290731874155
